getogrand_hypermedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", include("main.urls")),
]

main/urls.py
from django.urls import path

from .views import index, sentry_tunnel

app_name = "main"
urlpatterns = [
    path("sentry_tunnel", sentry_tunnel, name="sentry_tunnel"),
    path("", index, name="index"),
]

main/models.py
from django.db import models
from model_utils.models import TimeStampedModel


class Profile(TimeStampedModel):
    full_name = models.CharField()
    email = models.EmailField(unique=True)

    def __str__(self) -> str:
        return f"{self.full_name} ({self.email})"


class DateFramedModel(models.Model):
    start = models.DateField(null=True, blank=True)
    end = models.DateField(null=True, blank=True)

    class Meta:
        abstract = True


class Experience(TimeStampedModel, DateFramedModel):
    profile = models.ForeignKey(to=Profile, on_delete=models.CASCADE)
    story = models.TextField()
    company_name = models.CharField()
    positions: models.JSONField[list[str]] = models.JSONField(
        help_text="array of string"
    )

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.profile.save()

    def __str__(self) -> str:
        return self.company_name


class Duty(TimeStampedModel, DateFramedModel):
    experience = models.ForeignKey(to=Experience, on_delete=models.CASCADE)
    title = models.CharField()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.experience.save()

    def __str__(self) -> str:
        return self.title


class DutyItem(TimeStampedModel):
    duty = models.ForeignKey(to=Duty, on_delete=models.CASCADE)
    title = models.CharField()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.duty.save()

    def __str__(self) -> str:
        return self.title


class DutySubitem(TimeStampedModel):
    duty_item = models.ForeignKey(to=DutyItem, on_delete=models.CASCADE)
    title = models.CharField()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.duty_item.save()

    def __str__(self) -> str:
        return self.title

main/forms.py
from django import forms

from .models import Profile


class ProfileForm(forms.Form):
    expanded_experience_ids = forms.TypedMultipleChoiceField(
        coerce=int,
        widget=forms.SelectMultiple(attrs={"class": "hidden", "hx-swap-oob": "true"}),
        required=False,
    )

    def __init__(self, profile: Profile, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["expanded_experience_ids"].choices = [
            (experience.id, experience.company_name)
            for experience in profile.experience_set.all()
        ]

main/views.py
import re
import json
import requests
from urllib.parse import urlparse, ParseResult
from django.core.exceptions import BadRequest
from django.http import HttpRequest, HttpResponse
from django.template import loader
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import last_modified
from django.views.decorators.vary import vary_on_headers
from django.views.decorators.cache import cache_control

from .forms import ProfileForm
from .models import Profile


@cache_control(s_maxage=3600, stale_while_revalidated=60)
@vary_on_headers("HX-Target")
@last_modified(
    lambda req: Profile.objects.only("modified").get(email="getogrand@hey.com").modified
)
def index(request: HttpRequest) -> HttpResponse:
    profile = Profile.objects.prefetch_related(
        "experience_set__duty_set__dutyitem_set__dutysubitem_set",
    ).get(email="getogrand@hey.com")

    form = ProfileForm(profile=profile, data=request.GET if request.GET else None)
    form.full_clean()

    hx_target = request.headers.get("HX-Target")

    if not hx_target:
        return render(
            request=request,
            template_name="main/index.html",
            context={"profile": profile, "form": form},
        )

    if target_match := re.search(r"experience-(\d+)-(details|expand)", hx_target):
        experience_id = target_match.group(1)
        experience = profile.experience_set.get(pk=int(experience_id))
        render_results = [
            loader.render_to_string(
                template_name="main/index.html#experience_details",
                context={
                    "experience": experience,
                    "form": form,
                },
            ),
            loader.render_to_string(
                template_name="main/index.html#select", context={"form": form}
            ),
        ]
        return HttpResponse("\n".join(render_results))
    else:
        raise Exception(f"unknown target: {hx_target}")


@csrf_exempt
def sentry_tunnel(request: HttpRequest) -> HttpResponse:
    envelope = request.body
    piece = envelope.splitlines()[0]
    header = json.loads(piece)
    dsn: ParseResult = urlparse(header["dsn"])
    project_id: str = dsn.path.replace("/", "")

    sentry_hostname = "o303432.ingest.us.sentry.io"
    if dsn.hostname != sentry_hostname:
        raise BadRequest(f"invalid dsn hostname: {dsn.hostname}")
    if project_id != "4507459219685376":
        raise BadRequest(f"invalid project id: {project_id}")

    upstream_sentry_url = f"https://{sentry_hostname}/api/{project_id}/envelope/"
    requests.post(upstream_sentry_url, envelope)
    return HttpResponse("")

main/templates/main/index.html
{% extends "base.html" %}

{% load partials %}
{% load static %}

{% block title_prefix %}main{% endblock title_prefix %}

{% partialdef experience_details %}
{% if experience.id in form.cleaned_data.expanded_experience_ids %}
<article id="experience-{{ experience.id }}-details" class="grid not-prose font-sans mt-8">
  <div class="flex flex-col overflow-hidden">
    <section class="flex justify-between items-baseline">
      <h3 id="experience-{{ experience.id }}-company_name" class="text-xl">{{ experience.company_name }}</h3>
      <div id="experience-{{ experience.id }}-duration" class="text-sm text-gray-400 font-sans-light">
        <time datetime="{{ experience.start|date:"Y-m" }}">{{ experience.start|date:"Y.m" }}</time> ~ <time datetime="{{ experience.end|date:"Y-m" }}">{{ experience.end|date:"Y.m" }}</time>
      </div>
    </section>

    <ul id="experience-{{ experience.id }}-positions" class="text-sm leading-relaxed font-sans-light mt-1">
      {% for position in experience.positions %}<li><span>{{ position }}</span></li>{% endfor %}
    </ul>

    <ul id="experience-{{ experience.id }}-duties" class="mt-4 mb-5 flex flex-col gap-7">
      {% for duty in experience.duty_set.all %}
      <li>
        <article>
          <section class="flex flex-wrap justify-between items-baseline mb-2">
            <h4>{{ duty.title }}</h4>
            {% if duty.start %}
            <div class="text-sm text-gray-400 font-sans-light text-right grow">
              <time datetime="{{ duty.start|date:"Y-m" }}">{{ duty.start|date:"Y.m" }}</time> ~ <time datetime="{{ duty.end|date:"Y-m" }}">{{ duty.end|date:"Y.m" }}</time>
            </div>
            {% endif %}
          </section>
          <ul class="font-sans-light text-sm leading-relaxed flex flex-col gap-4">
            {% for duty_item in duty.dutyitem_set.all %}
            <li>
              {{ duty_item.title }}
              {% if duty_item.dutysubitem_set.all %}
              <ul class="ml-6 list-disc list-outside flex flex-col gap-1 mt-2">
                {% for subitem in duty_item.dutysubitem_set.all %}
                <li>{{ subitem.title }}</li>
                {% endfor %}
              </ul>
              {% endif %}
            </li>
            {% endfor %}
          </ul>
        </article>
      </li>
      {% endfor %}
    </ul>

    <button
      id="experience-{{ experience.id }}-collapse" type="submit"
      class="prose font-serif before:content-['↼_'] mb-6 self-end"
      hx-get="/" hx-target="#experience-{{ experience.id }}-details"
      hx-swap="outerHTML swap:0.6s"
      hx-vals="js:{expanded_experience_ids: getExpandedExperienceIds().filter(id => id !== '{{ experience.id }}')}"
      _="on click js document.getElementById('experience-{{ experience.id }}').scrollIntoView({behavior: 'smooth'}) end">
      관련 경력 사항 가리기
    </button>
    <img class="w-24 self-center mt-14 mb-8" src="{% static "main/noun-plant-2215382.svg" %}" />
  </div>
</article>
{% else %}
<button
  id="experience-{{ experience.id }}-expand" type="submit"
  class="before:content-['⇀_'] mb-6 self-start"
  hx-get="/" hx-swap="outerHTML swap:0.3s"
  hx-vals="js:{expanded_experience_ids: getExpandedExperienceIds().concat(['{{ experience.id }}'])}">
  관련 경력 사항 보기
</button>
{% endif %}
{% endpartialdef %}

{% partialdef experience %}
{% with select_id=form.expanded_experience_ids.auto_id %}
<article id="experience-{{ experience.id }}" class="flex flex-col">
  <p id="experience-{{ experience.id }}-story" class="indent-2">{{ experience.story }}</p>
</article>
{% partial experience_details %}
{% endwith %}
{% endpartialdef %}

{% block container_content %}
<form action="/" method="get" hx-replace-url="true">
  <article class="p-4 mt-8 mb-24 prose font-serif">
    <p class="indent-2">안녕하세요. 주원영입니다. 2013년부터 소프트웨어 개발자로 일하며 살고 있습니다. 연락은 <a href="mailto:getogrand@hey.com">getogrand@hey.com</a>으로 부탁드립니다. 단순 수다, 업계 이야기, 기술에 대한 문의/논의 및 이를 위한 커피챗 요청 환영합니다.</p>

    <h2 id="accounts" class="group"><a href="#accounts" class="no-underline hover:underline decoration-gray-500 relative"><span class="hidden sm:group-hover:inline-block sm:group-target:inline-block sm:absolute sm:-start-5 sm:text-gray-500">#</span>계정들</a></h2>

    <ul>
      <li><a class="no-underline flex flex-wrap items-baseline gap-x-1" href="https://x.com/getogrand" target="_blank"><span class="underline">Twitter(𝕏)</span><span class="text-xs text-gray-400">https://x.com/getogrand</span></a></li>
      <li><a class="no-underline flex flex-wrap items-baseline gap-x-1" href="https://github.com/getogrand" target="_blank"><span class="underline">GitHub</span><span class="text-xs text-gray-400">https://github.com/getogrand</span></a></li>
      <li><a class="no-underline flex flex-wrap items-baseline gap-x-1" href="https://www.instagram.com/getogrand_" target="_blank"><span class="underline">Instagram</span><span class="text-xs text-gray-400">https://www.instagram.com/getogrand_</span></a></li>
      <li><a class="no-underline flex flex-wrap items-baseline gap-x-1" href="https://www.linkedin.com/in/wonyoung-ju" target="_blank"><span class="underline">LinkedIn</span><span class="text-xs text-gray-400">https://www.linkedin.com/in/wonyoung-ju</span></a></li>
      <li><a class="no-underline flex flex-wrap items-baseline gap-x-1" href="https://stackoverflow.com/users/12509847/getogrand" target="_blank"><span class="underline">StackOverflow</span><span class="text-xs text-gray-400">https://stackoverflow.com/users/12509847/getogrand</span></a></li>
      <li><a class="no-underline flex flex-wrap items-baseline gap-x-1" href="https://xn--o39a90m89r.com/@getogrand" target="_blank"><span class="underline">적독가(積讀家)</span><span class="text-xs text-gray-400">https://xn--o39a90m89r.com/@getogrand</span></a></li>
    </ul>

    <h2 id="career" class="group"><a href="#career" class="group no-underline hover:underline decoration-gray-500 relative"><span class="hidden sm:group-hover:inline-block sm:group-target:inline-block sm:absolute sm:-start-5 sm:text-gray-500">#</span>커리어</a></h2>

    {% with select_id=form.expanded_experience_ids.auto_id %}
    {% for experience in profile.experience_set.all %}
    <article id="experience-{{ experience.id }}" class="flex flex-col {% if forloop.first %}-mt-4{% endif %}">
      <p id="experience-{{ experience.id }}-story" class="indent-2">{{ experience.story }}</p>
    </article>
    {% partial experience_details %}
    {% endfor %}
    {% endwith %}

    <p class="indent-2">다음 커리어는 다시 Full-Stack 웹 개발자 혹은 백엔드 개발자로 생각하고 있습니다. HTML-over-the-wire 류의 기술과 Full-Stack 프레임워크를 함께 써서 제가 생각한 합리적인 기술 스택을 직접 검증해 보고 싶습니다. 기술적 검증에 성공하고 비즈니스도 잘 되어 과연 이 스택으로 어디까지 스케일업이 가능한지 확인할 수 있다면 더할 나위 없이 좋겠습니다.</p>
  </article>

  {% partialdef select inline=True %}{{ form.expanded_experience_ids }}{% endpartialdef %}
</form>

<style>
article[id^=experience-][id$=-details] {
  opacity: 1;
  grid-template-rows: 1fr;
  transition: opacity 0.3s ease-out 0.3s, grid-template-rows 0.3s ease-out 0.3s;
}
article[id^=experience-][id$=-details].htmx-swapping,
article[id^=experience-][id$=-details].htmx-added {
  overflow: hidden;
  min-height: 0;
  opacity: 0;
  grid-template-rows: 0fr;
}

button[id^=experience-][type=submit] {
  opacity: 1;
  transition: opacity 0.3s ease-out;
}
button[id^=experience-][type=submit].htmx-swapping,
button[id^=experience-][type=submit].htmx-added {
  opacity: 0;
}
</style>
<script>
/**
 * @returns {string[]}
 */
function getExpandedExperienceIds() {
  return Array.from(
    document.getElementById('{{ form.expanded_experience_ids.auto_id }}').selectedOptions
  ).map(opt => opt.value)
}
</script>
{% endblock container_content %}

theme/templates/base.html
{% load static %}
{% load static tailwind_tags %}
<!doctype html>
<html lang="ko-KR">
	<head>
    <title>{% if debug %}[DEV] {% endif %}{% block title_prefix %}{% endblock title_prefix %} - getogrand's hypermedia</title>
		<meta name="author" content="Wonyoung Ju">
    <meta name="description" content="getogrand's hypermedia collection.">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<meta name="htmx-config" content='{"scrollBehavior":"auto", "triggerSpecsCache": {}, "allowNestedOobSwaps": false}'>
		<link rel="preload" href="{% static "fonts/GowunBatang-Regular.woff2" %}" as="font" type="font/woff2" crossorigin>
		<link rel="preload" href="{% static "fonts/S-CoreDream-5Medium.woff2" %}" as="font" type="font/woff2" crossorigin>
		<link rel="preload" href="{% static "fonts/S-CoreDream-3Light.woff2" %}" as="font" type="font/woff2" crossorigin>
		<link rel="apple-touch-icon" sizes="57x57" href="{% static "images/icons/apple-icon-57x57.png" %}">
		<link rel="apple-touch-icon" sizes="60x60" href="{% static "images/icons/apple-icon-60x60.png" %}">
		<link rel="apple-touch-icon" sizes="72x72" href="{% static "images/icons/apple-icon-72x72.png" %}">
		<link rel="apple-touch-icon" sizes="76x76" href="{% static "images/icons/apple-icon-76x76.png" %}">
		<link rel="apple-touch-icon" sizes="114x114" href="{% static "images/icons/apple-icon-114x114.png" %}">
		<link rel="apple-touch-icon" sizes="120x120" href="{% static "images/icons/apple-icon-120x120.png" %}">
		<link rel="apple-touch-icon" sizes="144x144" href="{% static "images/icons/apple-icon-144x144.png" %}">
		<link rel="apple-touch-icon" sizes="152x152" href="{% static "images/icons/apple-icon-152x152.png" %}">
		<link rel="apple-touch-icon" sizes="180x180" href="{% static "images/icons/apple-icon-180x180.png" %}">
		<link rel="icon" type="image/png" sizes="192x192"  href="{% static "images/icons/android-icon-192x192.png" %}">
		<link rel="icon" type="image/png" sizes="32x32" href="{% static "images/icons/favicon-32x32.png" %}">
		<link rel="icon" type="image/png" sizes="96x96" href="{% static "images/icons/favicon-96x96.png" %}">
		<link rel="icon" type="image/png" sizes="16x16" href="{% static "images/icons/favicon-16x16.png" %}">
		<link rel="manifest" href="{% static "pwa/manifest.json" %}">
		<meta name="msapplication-TileColor" content="#ffffff">
		<meta name="msapplication-TileImage" content="{% static "images/icons/ms-icon-144x144.png" %}">
		<meta name="theme-color" content="#ffffff">
		<style>
			@font-face {
				font-family: 'GowunBatang-Regular';
				src: url('{% static "fonts/GowunBatang-Regular.woff2" %}') format('woff2');
				font-weight: normal;
				font-display: swap;
			}

			@font-face {
				font-family: 'S-CoreDream-5Medium';
				src: url('{% static "fonts/S-CoreDream-5Medium.woff2" %}') format('woff2');
				font-weight: normal;
				font-display: swap;
			}

			@font-face {
				font-family: 'S-CoreDream-3Light';
				src: url('{% static "fonts/S-CoreDream-3Light.woff2" %}') format('woff2');
				font-weight: normal;
				font-display: swap;
			}

			html {
				font-size: 18px;
			}
		</style>

		{% if debug %}
			{% now "U" as timestamp %}
			{% tailwind_preload_css v=timestamp %}
			{% tailwind_css v=timestamp %}
		{% else %}
			{% tailwind_preload_css %}
			{% tailwind_css %}
		{% endif %}

		{% if not debug %}
		<script defer src="{% static "js/sentry.browser.8.10.0.min.js" %}" crossorigin="anonymous"></script>
		{% endif %}

		{% if debug %}
		<script defer src="{% static "js/_hyperscript.0.9.12.js" %}"></script>
		{% else %}
		<script defer src="{% static "js/_hyperscript.0.9.12.min.js" %}"></script>
		{% endif %}

		{% if debug %}
		<script defer src="{% static "js/htmx.2.0.0.js" %}"></script>
		{% else %}
		<script defer src="{% static "js/htmx.2.0.0.min.js" %}"></script>
		{% endif %}
	</head>

	<body class="bg-gray-50 leading-relaxed tracking-normal font-sans break-keep break-words whitespace-normal text-pretty" hx-boost="true"
		{% if debug %}_="on load js htmx.logAll()"{% endif %}
	>
		<header class="mx-4 mb-2 px-1 pt-4 pb-1 border-b-2 border-gray-800 uppercase text-xl">
			<a href="/" class="align-middle">getogrand's hypermedia</a>
		</header>
		<div class="container mx-auto">
			{% block container_content %}{% endblock container_content %}
		</div>
	</body>

	{% if not debug %}
	<script type="text/hyperscript">
		on load js {
			Sentry.init({
				dsn: "https://014368f40281b9972cbb18d0d5222803@o303432.ingest.us.sentry.io/4507459219685376",
				tunnel: "/sentry_tunnel"
			});
		}
	</script>
	{% endif %}
</html>